### PR TITLE
Login page effects added

### PR DESCRIPTION
**Pull request by agr1ms**

### CODE REVIEW

**Comment by 7saikat7** [comment]
please share screenshort

**Comment by agr1ms** [comment]
Sharing

**Comment by agr1ms** [comment]
Normal buttons:
image

hover effect on sign-up:
image

hover effect on submit:
image

hover on inputs:
image

At the time of clicking on either input:
image

Removed the shadow effects on texts in the nav-bar:
image

Login button hover effect:
image

**Comment by Rushijaviya** [comment]
#73

**Pull request merged**
