### PR TITLE
created login page

### PR DESCRIPTION
**Pull request by codervivek5**
I have created a login page for the website.

### CODE REVIEW

**Comment by 7saikat7** [comment]
please mention the issue no or link once in which you are working

**Comment by codervivek5** [comment]
There is no any issue regarding login page so i have created it....you may checkout it...this designed it referenced by Figma design...

**Comment by codervivek5** [comment]
Issue #39 i have created it...plz checkout it.

**Comment by 7saikat7** [comment]
Create a issues and then comment on there to get assigned

**Pull request closed without merging**
