### PR TITLE
Create add delivery feature #61

### PR DESCRIPTION
**Pull request by akhil484**
I have created 
    - View
    - Template
    - urls
I have updated models.py inside the inventory app,
I have also created a simple HTML form to get the data filled by the user inside the view.

### CODE REVIEW

**Comment by akhil484** [comment]
Hi, Can you help me with fixing this issue?

**Comment by 7saikat7** [comment]
sure , you are having a merge conflict try to resolve on ping please on discord group

**Comment by Rushijaviya** [comment]
@akhil484, you are not saving the input data. Once we get the input from the form, we need to save it in the database. Please save it for the record.

**Comment by akhil484** [comment]
Okay, I will do the following changes

**Comment by Rushijaviya** [comment]
> Okay, I will do the following changes

any update !

**Comment by akhil484** [comment]
I will try to commit the PR before tomorrow's EOD.

**Comment by Rushijaviya** [comment]
#61

**Pull request merged**
